### ISSUE TITLE
Contribution : Packer template

### ISSUE THREAD

**Issue by UmanGarbag** [fduran/sadservers#2]
Hello, 

I would like to contribute to this cool project by providing you a packer code that i have made for different provider (vsphere,proxmox).

The code is able to create Ubuntu 20.04,22.04 template with different preinstalled package, and user account with sudo permissions.

I think i just need to adapt it to aws provider.

Can you provide me a list a requirements you want in you image ?

**Comment by UmanGarbag** [comment]
Do you have a discord for discuss about the project ?

**Comment by fduran** [comment]
@UmanGarbag I'm fduran at hangops.slack.com and at /r/sre on Discord or email me at info@sadservers.com thanks!
