### ISSUE TITLE
Using wasm linux

### ISSUE THREAD

**Issue by user753** [fduran/sadservers#3]
Hi. Thanks for the great project. 
Was it considered to use wasm linux in browser? 
It would reduce AWS bill and it would be possible to use it offline.

**Comment by fduran** [comment]
Thanks for the feedback. Yes, I want to look into using WASM, which allows for just "downloading" it which should be cheaper and there are no security concerns (for me). OTOH it loses the idea of checking the solution and keeping track of what the user has done so far (this not implemented yet).  

Docker images (and image or images with docker-compose.yaml for ex) could be also an option as an easier way to allow download/offline scenarios.

**Comment by user753** [comment]
thanks
