### ISSUE TITLE
Curated problem solutions

### ISSUE THREAD

**Issue by celia-vytrac** [fduran/sadservers#4]
Do you know where we can see other users' scripts for the different problems? It would be helpful if there were a place to discuss problem solutions. I can, for instance, solve a problem in a very roundabout fashion without grasping the true essence of the lesson. Seeing how others completed the different exercises after submitting a correct solution would be helpful.

**Comment by fduran** [comment]
Thanks for your feedback.  

There are three not mutually exclusive options I've been thinking about to help with this:  
- Create or support a forum, either in SadServers website itself or hosted somewhere else.
- Keeping track in this repo of my original scenario solutions (and descriptions and tests) and curate some alternative solutions
- Implement a feature where I store the users command history in the VM and flag when they arrived to a successful test. This way I could implement a fun feature of a button for "Show me how other people solved this" and pick randomly (or by less time used) a solution.

**Comment by jd-apprentice** [comment]
> Thanks for your feedback.
> 
> There are three not mutually exclusive options I've been thinking about to help with this:
> 
>     * Create or support a forum, either in SadServers website itself or hosted somewhere else.
> 
>     * Keeping track in this repo of my original scenario solutions (and descriptions and tests) and curate some alternative solutions
> 
>     * Implement a feature where I store the users command history in the VM and flag when they arrived to a successful test. This way I could implement a fun feature of a button for "Show me how other people solved this" and pick randomly (or by less time used) a solution.

Or you can create a discord community and people could share their solutions there!

But yeah also is cool what celia mentions, maybe something like Codewars but thats way too much to ask hahaha

**Comment by fduran** [comment]
Haven't forgotten about this :-) 

Updating:
- Added creating a user comment system in the TODO
- discord/slack will probably come at some point
- there is a [video replay system ](https://replay.sadservers.com/explore)in place for some scenarios, with links to the user dashboard. TODO is to add link to examples of solved scenarios in the replay server
