### ISSUE TITLE
Not working "Run" because CSRF verification failed

### ISSUE THREAD

**Issue by qiyuren** [fduran/sadservers#48]
"Run" in any scenario does not work.

`Forbidden (403) CSRF verification failed.`

My Using browsers (safari, GoogleChrome (v119.0.6045.159)) allow cookies, but I got a 403 with the above error.

You might find an article about this error that says there is no CSRF token in the form.

Could you investigate this Or give me any solutions?

**Comment by cvbn55688** [comment]
I'm having this same issue.

**Comment by peter279k** [comment]
I've the same issue, too. Maybe the server has some problems.

After signing in the account, I see that my dashboard is worked, but the scenario is not worked.

**Comment by peter279k** [comment]
After testing that, the issue seems to be resolved now.

**Comment by fduran** [comment]
Hello, five days ago I added CSRF token to the "RUN" button in the /scenarios and /scenario pages. I also added caching yesterday. Almost sure csrf token issues go away with refreshing the page or navigating. 

Still I'm going to investigate and I'm inclined into taking csrf out of "run" buttons (there's no info passed in the form so kind of not needed but there's a reason I wanted to put it there)

**Comment by fduran** [comment]
I haven't seen any more 403 errors after disabling caching, closing

**Comment by qiyuren** [comment]
I have checked it. Thanx!
