### ISSUE TITLE
How to copy/paste in the terminal?

### ISSUE THREAD

**Issue by movergan** [fduran/sadservers#5]
Hello,

I would like to know if there is any hotkey I can use for copying and pasting in the terminal. 
Thanks

**Comment by fduran** [comment]
Hello, there's no special hotkey; it should work as in pasting in a browser. For example I use command-c command-v in Mac + Chrome.

**Comment by c4p1t4n** [comment]
You can use ctrl+ shift + c to copy and ctrl+shift+ v to paste. I think this will resolve your problem
