### ISSUE TITLE
Error in the Santiago

### ISSUE THREAD

**Issue by sudmed** [fduran/sadservers#50]
Hi, help me please to resolve my issue.
```bash
admin@i-068844a34e82f4dae:~$ grep -rwc "Alice" /home/admin/*.txt
/home/admin/11-0.txt:397
/home/admin/1342-0.txt:1
/home/admin/1661-0.txt:12
/home/admin/84-0.txt:0
```

```bash
admin@i-068844a34e82f4dae:~$ grep -rwc "Alice" /home/admin/*.txt | awk -F ':' '{total += $2} END {print total}'
410
```

```bash
admin@i-068844a34e82f4dae:~$ grep -l "Alice" /home/admin/1342-0.txt | xargs awk '/Alice/ {getline; print $1}'
156
```

The answer "410156" is not the solution, but the "411156" is. 
Could you explain where I have the error?

**Comment by fduran** [comment]
thanks for bringing this up, added to the [current overall issues with the scenario](https://github.com/fduran/sadservers/issues/10), that needs to be re-written so there's a clear problem statement and a single clear solution.
