### ISSUE TITLE
Requirements to write/record and publish scenarios solving content

### ISSUE THREAD

**Issue by slucasandrade** [fduran/sadservers#7]
Is there any problem/requirement on writing/recording the scenarios being solved in a Youtube Channel or Medium article? Thanks in advance and well done, SadServers is amazing!

**Comment by fduran** [comment]
Hello Lucas, there's no problem at all on writing/recording scenarios, please go ahead! 

I'd like to see and promote the result, please let me know (https://twitter.com/sadservers_com , info@sadservers.com etc) if you create any content, obrigado!
