### ISSUE TITLE
Replays

### ISSUE THREAD

**Issue by jd-apprentice** [fduran/sadservers#8]
Hey! Replays are intended to work or have been implemented just for the LWC and then forgot to remove it?

Because I've tried a scenario and it generated the followed link:

```
https://sadservers.com/accounts/View%20the%20recording%20at:
```

Just in case

![image](https://github.com/fduran/sadservers/assets/68082746/b8d3ffb4-dc2e-4844-aabb-4a32a8667f6c)

The scenario was that and what I've done was nothing weird. Just tried the scenario and got kicked out because no time left.

**Comment by fduran** [comment]
Hello, replays are intended to work in recent scenarios (the ones for the LWC and after) so yes, if you try one of them like "The Command Line Murders" it should show up in [https://replay.sadservers.com/](https://replay.sadservers.com/) (unless the replay file is too large or there was some other issue). Even after running out of time, the replay file should be uploaded and linked in your dashboard.
